 <?php
 // module/Album/view/album/album/index.phtml:

 $title = 'User Management';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 

 <table class="table">
 <tr>
     <th>Name</th>
     <th>User ID/Email</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($users as $user) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($user->name);?></td>
     <td><?php echo $this->escapeHtml($user->email);?></td>
     <td>
         <a href="<?php echo $this->url('users/user-manager',
             array('action'=>'edit', 'id' => $user->id));?>">Edit</a>
         <a href="<?php echo $this->url('users/user-manager',
             array('action'=>'delete', 'id' => $user->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>


